#log:
  #path: 'fileadmin/custom_path/test.log'
sources:
  Pixelant\PxaPmImporter\Service\Source\ExcelSource:
    skipRows: 1
    filePath: EXT:pxa_pm_importer/Resources/Private/ExampleData/products.xlsx
importers:
  ProductsImport:
    # Unique identifier field provided by Adapter
    identifierField: 'id'

    # Domain model name
    domainModel: Pixelant\PxaProductManager\Domain\Model\Product

    # Allowed import operations
    # default is 'create,localize,createLocalize'
    allowedOperations: 'create,localize'

    # Settings for new records
    importNewRecords:
      # Storage of new records
      pid: 440

    # Storage of records. Import will check storage for records
    storage:
      # Comma-separated list of folders
      pid: 440
      # Recursive level
      recursive: 0

    # Layer between raw data and importer
    adapter:
      className: 'Pixelant\PxaPmImporter\Adapter\DefaultDataAdapter'
      mapping:
        # Import unique identifier for all fields
        id: 'B'
        # Set this if excel columns instead of numbers is used
        excelColumns: true
        # Per language, field to excel column, A is first
        languages:
          0:
            name: 'A'
            sku: 'B'
            teaser: 'C'
            description: 'D'
            categories: 'E'
            brand: 'F'
            color: 'G'
            tireSize: 'H'
            engine: 'I'
            turboEngine: 'J'
            release: 'K'
            attributeFiles: 'S'
            attributeImages: 'T'
            images: 'L'
            assets: 'M'
            relatedProducts: 'N'
            subProducts: 'O'
            accessories: 'P'
            falLinks: 'Q'
            metaDescription: 'R'

    # Mapping fields, data adapter should return array with associative array
    mapping:
      name:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
        # Custom settings
        validation:
          - required
      sku:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      teaser:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      description:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      categories:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\CategoryProcessor'
      brand:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        # It's possible to specify just UID, set 'treatAttributeUidAsImportUid' to false
        attributeUid: 'brand'
        treatAttributeUidAsImportUid: true
      color:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'color'
        treatAttributeUidAsImportUid: true
      tireSize:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'tire-size'
        treatAttributeUidAsImportUid: true
      engine:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'engine'
        treatAttributeUidAsImportUid: true
      turboEngine:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'turbo-engine'
        treatAttributeUidAsImportUid: true
      release:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'release'
        dateFormat: 'H:i d-m-Y'
        treatAttributeUidAsImportUid: true
      attributeFiles:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'files'
        treatAttributeUidAsImportUid: true
        folder: 'import_files'
      attributeImages:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 'images'
        treatAttributeUidAsImportUid: true
        folder: 'import_files'
      images:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'import_files'
      assets:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'import_files'
      relatedProducts:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      subProducts:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      accessories:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      falLinks:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'import_files'
      metaDescription:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'