source:
  Pixelant\PxaPmImporter\Service\Source\ExcelSource:
    skipRows: 1
    filePath: EXT:pxa_pm_importer/Resources/Private/ExampleData/products.xlsx
importers:
  Pixelant\PxaPmImporter\Service\Importer\ProductsImporter:
    # Layer between raw data and importer
    adapter:
      className: 'Pixelant\PxaPmImporter\Adapter\DefaultDataAdapter'
      mapping:
        # Import unique identifier for all fields
        id: 'B'
        # Per language, field name to column from raw data, 0 is first
        languages:
          0:
            name: 'A'
            sku: 'B'
            teaser: 'C'
            description: 'D'
            categories: 'E'
            brand: 'F'
            color: 'G'
            tireSize: 'H'
            engine: 'I'
            turboEngine: 'J'
            release: 'K'
            images: 'L'
            assets: 'M'
            relatedProducts: 'N'
            subProducts: 'O'
            accessories: 'P'
            falLinks: 'Q'
            metaDescription: 'R'

    # Default
    identifierField: 'id'
    # Storage
    pid: 136

    # Mapping fields, data adapter should return array with associative array
    mapping:
      name:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
        # Custom settings
        validation: 'required'
      sku:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      teaser:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      description:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'
      categories:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\CategoryProcessor'
      brand:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 1
      color:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 2
      tireSize:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 3
      engine:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 4
      turboEngine:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 5
      release:
        processor: 'Pixelant\PxaPmImporter\Processors\ProductAttributeProcessor'
        attributeUid: 6
        dateFormat: 'H:i d-m-Y'
      images:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'importers'
      assets:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'importers'
      relatedProducts:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      subProducts:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      accessories:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\RelatedProductsProcessor'
      falLinks:
        processor: 'Pixelant\PxaPmImporter\Processors\Relation\Files\LocalFileProcessor'
        folder: 'importers'
      metaDescription:
        processor: 'Pixelant\PxaPmImporter\Processors\StringProcessor'